import { Page } from "../components/page.slint";
import { Styling } from "../assets/styles.slint";
import {
    GroupBox,
    VerticalBox,
    LineEdit,
    TextEdit,
    HorizontalBox,
    Button,
} from "std-widgets.slint";

import { PersonalData } from "../models/personal_info.slint";

export component PersonalPage inherits Page {
    title: "Personal Info";

    // Receives and sends two-way updates from AppWindow
    in-out property <PersonalData> personal_data;

    callback save-personal-info(PersonalData);

    function run() {
        root.save-personal-info(root.personal_data);
    }

    GroupBox {
        VerticalBox {
            HorizontalBox {
                alignment: start;
                padding: 0px;
                spacing: 5px;
                Button {
                    max-width: 50px;
                    text: "Save";
                    primary: true;

                    clicked => {
                        run()
                    }
                }
            }

            spacing: Styling.default-spacing;
            alignment: start;
            padding: Styling.default-padding;

            Text {
                text: "CV Name";
                font-size: Styling.font-size-normal;
            }

            LineEdit {
                placeholder-text: "My CV";
                text <=> root.personal_data.cv-name;
                input-type: text;
                font-size: Styling.font-size-normal;
                accepted => {
                    run();
                }
            }

            HorizontalBox {
                spacing: Styling.default-spacing;
                padding: Styling.default-padding;

                Text {
                    text: "Name";
                    font-size: Styling.font-size-normal;
                }

                LineEdit {
                    placeholder-text: "John Doe";
                    text <=> root.personal_data.name;
                    input-type: text;
                    font-size: Styling.font-size-normal;
                    accepted => {
                        run();
                    }
                }

                Text {
                    text: "Job Title";
                    font-size: Styling.font-size-normal;
                }

                LineEdit {
                    placeholder-text: "Data Scientist";
                    text <=> root.personal_data.job-title;
                    input-type: text;
                    font-size: Styling.font-size-normal;
                    accepted => {
                        run();
                    }
                }
            }

            HorizontalBox {
                spacing: Styling.default-spacing;
                padding: Styling.default-padding;
                Text {
                    text: "E-mail";
                    font-size: Styling.font-size-normal;
                }

                LineEdit {
                    placeholder-text: "email@example.com";
                    text <=> root.personal_data.email;
                    input-type: text;
                    font-size: Styling.font-size-normal;
                    accepted => {
                        run();
                    }
                }

                Text {
                    text: "Phone";
                    font-size: Styling.font-size-normal;
                }

                LineEdit {
                    placeholder-text: "+40 1234 5678";
                    text <=> root.personal_data.phone;
                    input-type: text;
                    font-size: Styling.font-size-normal;
                    accepted => {
                        run();
                    }
                }

                Text {
                    text: "Location";
                    font-size: Styling.font-size-normal;
                }

                LineEdit {
                    placeholder-text: "Romania";
                    text <=> root.personal_data.location;
                    input-type: text;
                    font-size: Styling.font-size-normal;
                    accepted => {
                        run();
                    }
                }
            }

            HorizontalBox {
                spacing: Styling.default-spacing;
                padding: Styling.default-padding;

                Text {
                    text: "Linked-In";
                    font-size: Styling.font-size-normal;
                }

                LineEdit {
                    placeholder-text: "https://www.linkedin.com/in/jdoe";
                    text <=> root.personal_data.linkedin;
                    input-type: text;
                    font-size: Styling.font-size-normal;
                    accepted => {
                        run();
                    }
                }

                Text {
                    text: "GitHub";
                    font-size: Styling.font-size-normal;
                }

                LineEdit {
                    placeholder-text: "https://github.com/jdoe";
                    text <=> root.personal_data.github;
                    input-type: text;
                    font-size: Styling.font-size-normal;
                    accepted => {
                        run();
                    }
                }

                Text {
                    text: "Website";
                    font-size: Styling.font-size-normal;
                }

                LineEdit {
                    placeholder-text: "https://jdoe.dev";
                    text <=> root.personal_data.website;
                    input-type: text;
                    font-size: Styling.font-size-normal;
                    accepted => {
                        run();
                    }
                }
            }

            Text {
                text: "Description";
                font-size: Styling.font-size-normal;
            }

            TextEdit {
                placeholder-text: "Description";
                text <=> root.personal_data.description;
                wrap: word-wrap;
                font-size: Styling.font-size-normal;
                enabled: true;
                width: 100%;
                height: 120px;
            }
        }
    }
}