import { Page } from "../components/page.slint";
import { Styling } from "../assets/styles.slint";
import {
    GroupBox,
    VerticalBox,
    LineEdit,
    TextEdit,
    HorizontalBox,
    Button,
} from "std-widgets.slint";

export component PersonalPage inherits Page {
    title: "Personal Info";

    in-out property <string> cv-name;
    in-out property <string> field-name;
    in-out property <string> field-job-title;
    in-out property <string> field-email;
    in-out property <string> field-phone;
    in-out property <string> field-location;
    in-out property <string> field-linkedin;
    in-out property <string> field-github;
    in-out property <string> field-website;
    in-out property <string> field-description;

    callback save-personal-info(string, string, string, string, string, string, string, string, string, string);

    function run() {
        root.save-personal-info(
            root.cv-name,
            root.field-name,
            root.field-job-title,
            root.field-email,
            root.field-phone,
            root.field-location,
            root.field-linkedin,
            root.field-github,
            root.field-website,
            root.field-description
        );
    }

    GroupBox {
        VerticalBox {
            HorizontalBox {
                alignment: start;
                padding: 0px;
                spacing: 5px;
                Button {
                    max-width: 50px;
                    text: "Save";
                    primary: true;

                    clicked => {
                        run()
                    }
                }
            }

            spacing: Styling.default-spacing;
            alignment: start;
            padding: Styling.default-padding;

            Text {
                text: "CV Name";
                font-size: Styling.font-size-normal;
            }

            LineEdit {
                placeholder-text: "My CV";
                text <=> root.cv-name;
                input-type: text;
                font-size: Styling.font-size-normal;
                accepted => {
                    run();
                }
            }

            HorizontalBox {
                spacing: Styling.default-spacing;
                padding: Styling.default-padding;

                Text {
                    text: "Name";
                    font-size: Styling.font-size-normal;
                }

                LineEdit {
                    placeholder-text: "John Doe";
                    text <=> root.field-name;
                    input-type: text;
                    font-size: Styling.font-size-normal;
                    accepted => {
                        run();
                    }
                }

                Text {
                    text: "Job Title";
                    font-size: Styling.font-size-normal;
                }

                LineEdit {
                    placeholder-text: "Data Scientist";
                    text <=> root.field-job-title;
                    input-type: text;
                    font-size: Styling.font-size-normal;
                    accepted => {
                        run();
                    }
                }
            }

            HorizontalBox {
                spacing: Styling.default-spacing;
                padding: Styling.default-padding;
                Text {
                    text: "E-mail";
                    font-size: Styling.font-size-normal;
                }

                LineEdit {
                    placeholder-text: "email@example.com";
                    text <=> root.field-email;
                    input-type: text;
                    font-size: Styling.font-size-normal;
                    accepted => {
                        run();
                    }
                }

                Text {
                    text: "Phone";
                    font-size: Styling.font-size-normal;
                }

                LineEdit {
                    placeholder-text: "+40 1234 5678";
                    text <=> root.field-phone;
                    input-type: text;
                    font-size: Styling.font-size-normal;
                    accepted => {
                        run();
                    }
                }

                Text {
                    text: "Location";
                    font-size: Styling.font-size-normal;
                }

                LineEdit {
                    placeholder-text: "Romania";
                    text <=> root.field-location;
                    input-type: text;
                    font-size: Styling.font-size-normal;
                    accepted => {
                        run();
                    }
                }
            }

            HorizontalBox {
                spacing: Styling.default-spacing;
                padding: Styling.default-padding;

                Text {
                    text: "Linked-In";
                    font-size: Styling.font-size-normal;
                }

                LineEdit {
                    placeholder-text: "https://www.linkedin.com/in/jdoe";
                    text <=> root.field-linkedin;
                    input-type: text;
                    font-size: Styling.font-size-normal;
                    accepted => {
                        run();
                    }
                }

                Text {
                    text: "GitHub";
                    font-size: Styling.font-size-normal;
                }

                LineEdit {
                    placeholder-text: "https://github.com/jdoe";
                    text <=> root.field-github;
                    input-type: text;
                    font-size: Styling.font-size-normal;
                    accepted => {
                        run();
                    }
                }

                Text {
                    text: "Website";
                    font-size: Styling.font-size-normal;
                }

                LineEdit {
                    placeholder-text: "https://jdoe.dev";
                    text <=> root.field-website;
                    input-type: text;
                    font-size: Styling.font-size-normal;
                    accepted => {
                        run();
                    }
                }
            }

            Text {
                text: "Description";
                font-size: Styling.font-size-normal;
            }

            TextEdit {
                placeholder-text: "Description";
                text <=> root.field-description;
                wrap: word-wrap;
                font-size: Styling.font-size-normal;
                enabled: true;
                width: 100%;
                height: 120px;
            }
        }
    }
}