import { SideBar } from "components/side_bar.slint";
import { PersonalPage } from "./pages/personal.slint";
import { PersonalInfo } from "models/personal_info.slint";

export component AppWindow inherits Window {
    title: "Resume Maker";
    maximized: false;

    preferred-width: 1000px;
    preferred-height: 700px;

    in-out property <[string]> resumes-list;

    in-out property <PersonalInfo> personal-info;

    callback menu-item-clicked(string, string); //(resume_name, action_type)
    callback save-personal-info(string, string, string, string, string, string, string, string, string, string);
    callback clear-all-fields();

    MenuBar {
        Menu {
            title: "Open";
            MenuItem {
                title: "Add";
                activated => {
                    clear-all-fields();
                }
            }
            MenuSeparator {}
            for resume in root.resumes-list: Menu {
                title: resume;
                if resume != "Add":MenuItem {
                    title: "Edit";
                    activated => {
                        menu-item-clicked(resume, "edit");
                    }
                }

                if resume != "Add": MenuItem {
                    title: "Delete";

                    activated => {
                        menu-item-clicked(resume, "delete");
                    }
                }
            }
        }
    }

    HorizontalLayout {

        side-bar := SideBar {
            accessible-role: navigation;
            accessible-label: "Sidebar";
            model: [
                "Personal Info",
            ];
        }

        VerticalLayout {
            accessible-role: main;
            accessible-label: "Content";
            if (side-bar.current-item == 0): PersonalPage {

                cv-name: root.cv-name;
                        field-name: root.field-name;
                        field-job-title: root.field-job-title;
                        field-email: root.field-email;
                        field-phone: root.field-phone;
                        field-location: root.field-location;
                        field-linkedin: root.field-linkedin;
                        field-github: root.field-github;
                        field-website: root.field-website;
                        field-description: root.field-description;

                save-personal-info(cv_name, name, job_title, email, phone, location, linkedin, github, website, description) => {
                    root.save-personal-info(cv_name, name, job_title, email, phone, location, linkedin, github, website, description);
                }
            }
        }
    }
}
