import { SideBar } from "components/side_bar.slint";
import { PersonalPage } from "./pages/personal.slint";


export component AppWindow inherits Window {
    title: "Resume Maker";
    maximized: false;

    preferred-width: 1000px;
    preferred-height: 700px;

    in-out property <[string]> resumes-list;

    in-out property <string> cv-name;
    in-out property <string> field-name;
    in-out property <string> field-job-title;
    in-out property <string> field-email;
    in-out property <string> field-phone;
    in-out property <string> field-location;
    in-out property <string> field-linkedin;
    in-out property <string> field-github;
    in-out property <string> field-website;
    in-out property <string> field-description;

    callback menu-item-clicked(string, string); //(resume_name, action_type)
    callback save-personal-info(string, string, string, string, string, string, string, string, string, string);

    MenuBar {
        Menu {
            title: "Open";
            for resume in root.resumes-list: Menu {
                title: resume;
                if resume != "Add":MenuItem {
                    title: "Edit";
                    activated => {
                        menu-item-clicked(resume, "edit");
                    }
                }

                if resume != "Add": MenuItem {
                    title: "Delete";

                    activated => {
                        menu-item-clicked(resume, "delete");
                    }
                }
            }
        }
    }

    HorizontalLayout {

        side-bar := SideBar {
            accessible-role: navigation;
            accessible-label: "Sidebar";
            model: [
                "Personal Info",
            ];
        }

        VerticalLayout {
            accessible-role: main;
            accessible-label: "Content";
            if (side-bar.current-item == 0): PersonalPage {
                save-personal-info(cv_name, name, job_title, email, phone, location, linkedin, github, website, description) => {
                    root.save-personal-info(cv_name, name, job_title, email, phone, location, linkedin, github, website, description);
                }
            }
        }
    }
}
